name: Godlint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  godlint:
    name: Check repository with Godlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tomerwave/godlint@e7677921fd0b234ef5e0a3e5d0d8f04fdb1a2f7b # v0.7.0
