name: Godlint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  godlint:
    name: Check repository with Godlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: tomerwave/godlint@7d079a7f4cdcf4dbb02f85aad8e3cc20feeaa544 # v1
